version: 1.0
services:
  - name: nodejs-app
    source:
      image: aws/codebuild/standard:5.0
      runtime: nodejs:14
      build:
        commands:
          - npm install
          - npm run go
          - npm run start
    port: 8080
    healthCheck:
      command: curl -f http://localhost:3000/ || exit 1
    environment:
      variables:
        NODE_ENV: production
